frappe.listview_settings['DocType'] = {
  get_additional_menu_items: function (list) {
    return [
      {
        label: __("Create Lookup Entity"),
        action: () => {
          const d = new frappe.ui.Dialog({
            title: __("Create Lookup Entity"),
            fields: [
              {
                fieldtype: "Data",
                fieldname: "name",
                label: "Name",
                reqd: true,
                onchange: function(e) {
                  if (!d.fields_dict.fieldname.get_value()) {
                    const fieldname = e.target.value.trim().toLowerCase().replace(/ /g, '_');
                    d.fields_dict.fieldname.set_value(fieldname);
                  }
                },
              },
              {
                fieldtype: "Data",
                fieldname: "fieldname",
                label: "Field Name",
                reqd: true,
              },
              {
                fieldtype: "Link",
                fieldname: "module",
                label: "Module",
                options: "Module Def",
                reqd: true,
              },
            ],
            primary_action_label: __("Create"),
            primary_action: (values) => {
              frappe.call({
                method: 'frappe.desk.form.save.savedocs',
                args: {
                  doc: {
                    docstatus: 0,
                    doctype: "DocType",
                    __islocal: 1,
                    __unsaved: 1,
                    owner: "Administrator",
                    is_submittable: 0,
                    istable: 0,
                    issingle: 0,
                    is_tree: 0,
                    editable_grid: 1,
                    quick_entry: 0,
                    track_changes: 1,
                    track_seen: 0,
                    track_views: 0,
                    custom: 0,
                    beta: 0,
                    is_virtual: 0,
                    naming_rule: "By fieldname",
                    name_case: "",
                    allow_rename: 1,
                    hide_toolbar: 0,
                    allow_copy: 0,
                    allow_import: 1,
                    allow_events_in_timeline: 0,
                    allow_auto_repeat: 0,
                    sort_field: "modified",
                    sort_order: "DESC",
                    document_type: "",
                    show_preview_popup: 0,
                    show_name_in_global_search: 1,
                    email_append_to: 0,
                    read_only: 0,
                    in_create: 0,
                    has_web_view: 0,
                    allow_guest_to_view: 0,
                    index_web_pages_for_search: 1,
                    engine: "InnoDB",
                    permissions: [
                      {
                        docstatus: 0,
                        doctype: "DocPerm",
                        name: "new-docperm-3",
                        __islocal: 1,
                        __unsaved: 1,
                        owner: "Administrator",
                        if_owner: 0,
                        permlevel: 0,
                        select: 0,
                        read: 1,
                        write: 1,
                        create: 1,
                        delete: 1,
                        submit: 0,
                        cancel: 0,
                        amend: 0,
                        report: 1,
                        export: 1,
                        import: 0,
                        set_user_permissions: 0,
                        share: 1,
                        print: 1,
                        email: 1,
                        parent: "new-doctype-2",
                        parentfield: "permissions",
                        parenttype: "DocType",
                        idx: 1,
                        role: "System Manager"
                      },
                      {
                        docstatus: 0,
                        doctype: "DocPerm",
                        name: "new-docperm-4",
                        __islocal: 1,
                        __unsaved: 1,
                        owner: "Administrator",
                        if_owner: 0,
                        permlevel: 0,
                        select: 0,
                        read: 1,
                        write: 0,
                        create: 0,
                        delete: 0,
                        submit: 0,
                        cancel: 0,
                        amend: 0,
                        report: 1,
                        export: 1,
                        import: 0,
                        set_user_permissions: 0,
                        share: 1,
                        print: 1,
                        email: 1,
                        parent: "new-doctype-2",
                        parentfield: "permissions",
                        parenttype: "DocType",
                        idx: 2,
                        __unedited: false,
                        role: "All"
                      }
                    ],
                    __newname: values.name,
                    module: values.module,
                    fields: [
                      {
                        docstatus: 0,
                        doctype: "DocField",
                        name: "new-docfield-1",
                        __islocal: 1,
                        __unsaved: 1,
                        owner: "Administrator",
                        fieldtype: "Data",
                        precision: "",
                        non_negative: 0,
                        hide_days: 0,
                        hide_seconds: 0,
                        reqd: 0,
                        search_index: 0,
                        show_dashboard: 0,
                        fetch_if_empty: 0,
                        hidden: 0,
                        bold: 0,
                        allow_in_quick_entry: 0,
                        translatable: 0,
                        print_hide: 0,
                        print_hide_if_no_value: 0,
                        report_hide: 0,
                        collapsible: 0,
                        hide_border: 0,
                        in_list_view: 0,
                        in_standard_filter: 0,
                        in_preview: 0,
                        in_filter: 0,
                        in_global_search: 0,
                        read_only: 0,
                        allow_on_submit: 0,
                        ignore_user_permissions: 0,
                        allow_bulk_edit: 0,
                        permlevel: 0,
                        ignore_xss_filter: 0,
                        unique: 0,
                        no_copy: 0,
                        set_only_once: 0,
                        remember_last_selected_value: 0,
                        parent: "new-doctype-2",
                        parentfield: "fields",
                        parenttype: "DocType",
                        idx: 1,
                        __unedited: false,
                        label: values.name,
                      }],
                    autoname: "field:" + values.fieldname,
                    default_import_order: values.fieldname,
                    title_field: values.fieldname,
                    search_fields: values.fieldname
                  },
                  action: 'Save',
                },
                callback: function (r) {
                  if (!r.exec) {
                    list.refresh();
                    d.hide();
                  }
                }
              });
            },
          });
          d.show();
        },
      },
    ];
  },
};
